name = "Metis Enhanced"
prefix = "mts"
author = "Bix, PhILoX, Timi007"
files = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "LICENSE",
    "mts_team_logo_small.paa",
    "meta.cpp"
]

modname = "Metis_Enhanced"
key_name = "mts_enhanced_{{version}}"
authority = "mts_enhanced_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip Metis_Enhanced_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version= "{{git \"id 8\"}}"
