name = "Metis_Enhanced"
mainprefix = "z"
prefix = "mts"
author = "Bix, PhILoX, Timi007"

[files]
include = [
    "mod.cpp",
    "README.md",
    "LICENSE",
    "mts_enhanced_picture.paa",
    "mts_enhanced_logo_small.paa",
    "mts_enhanced_logo_over_small.paa",
    "meta.cpp"
]

[signing]
authority = "mts_enhanced"

[version]
git_hash = 0

[hemtt.config]
preset = "Hemtt"

[hemtt.release]
folder = "Metis_Enhanced"

[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "463939057", # ACE3's Workshop ID
    "1779063631", # ZEN's Workshop ID
]
