name = "Metis_Enhanced"
mainprefix = "z"
prefix = "mts"
author = "Bix, PhILoX, Timi007"

[files]
include = [
    "mod.cpp",
    "README.md",
    "LICENSE",
    "mts_enhanced_picture.paa",
    "mts_enhanced_logo_small.paa",
    "mts_enhanced_logo_over_small.paa",
    "meta.cpp"
]

[signing]
authority = "mts_enhanced"

[version]
git_hash = 0

[asc]
enabled = true
exclude = [
    "/initsettings.sqf",
    "/initkeybinds.sqf",
    "/xeh_prep.sqf",
]

[hemtt.config]
preset = "Hemtt"

[hemtt.release]
folder = "Metis_Enhanced"
